name: Deploy to AWS

on:
  push:
    branches:
      - main
      - master

jobs:
  Deploy-to-AWS:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t ghcr.io/2000ghz/hello-2048/hello-2048:latest .
          docker push ghcr.io/2000ghz/hello-2048/hello-2048:latest

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
        env:
          AWS_AUDIENCE: sts.amazonaws.com
           
      
      - name: Launch EC2 instance from launch template
        run: |
            INSTANCE_ID=$(aws ec2 run-instances \
              --launch-template LaunchTemplateId=lt-0d54503baa0a64beb \
              --query "Instances[0].InstanceId" \
              --output text)
            echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
            aws ec2 wait instance-running --instance-ids $INSTANCE_ID
  
      - name: Get Instance Information
        run: |
              INSTANCE_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
              echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV
          
      - name: Comment IP address
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          body: "EC2 instance is available at: http://${{ env.INSTANCE_IP }}:80"
            
          
      - name: Echo IP address
        run: | 
          echo "EC2 instance is available at: http://$INSTANCE_IP:80"